# Generated by Django 5.2.2 on 2025-06-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_alter_customuser_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de départ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de retour'),
        ),
    ]
