# Generated by Django 5.2.2 on 2025-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0004_alter_message_options_remove_message_seen_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
