# Generated by Django 5.2.2 on 2025-06-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0005_offre_latitude_offre_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
