# Generated by Django 5.2.2 on 2025-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0006_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='date',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='heure',
        ),
        migrations.AddField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
