# Generated by Django 5.2.2 on 2025-06-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0007_remove_offre_date_remove_offre_heure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='PrivateMessage',
        ),
        migrations.RenameField(
            model_name='privatemessage',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
