# Generated by Django 5.2.3 on 2025-06-17 13:20

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
            },
        ),
        migrations.CreateModel(
            name='RideChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat de Trajet',
                'verbose_name_plural': 'Chats de Trajets',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='IFRI_comotorage.ridechat')),
            ],
            options={
                'verbose_name': 'Message de Chat',
                'verbose_name_plural': 'Messages de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=255)),
                ('departure_latitude', models.FloatField(blank=True, null=True)),
                ('departure_longitude', models.FloatField(blank=True, null=True)),
                ('arrival_location', models.CharField(max_length=255)),
                ('arrival_latitude', models.FloatField(blank=True, null=True)),
                ('arrival_longitude', models.FloatField(blank=True, null=True)),
                ('departure_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_time', models.TimeField(default=datetime.time(8, 0))),
                ('available_seats', models.PositiveIntegerField(default=1)),
                ('seats_taken', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offre de Trajet',
                'verbose_name_plural': 'Offres de Trajets',
                'ordering': ['departure_time'],
            },
        ),
        migrations.AddField(
            model_name='ridechat',
            name='ride_offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='IFRI_comotorage.rideoffer'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(blank=True, max_length=255, null=True)),
                ('horaire_debut', models.TimeField(blank=True, null=True)),
                ('horaire_fin', models.TimeField(blank=True, null=True)),
                ('nombre_places', models.PositiveIntegerField(default=1)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('type_utilisateur', models.CharField(choices=[('conducteur', 'Conducteur'), ('passager', 'Passager')], default='conducteur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('chat_access_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
                ('ride_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='IFRI_comotorage.rideoffer')),
            ],
            options={
                'verbose_name': 'Demande de Trajet',
                'verbose_name_plural': 'Demandes de Trajets',
                'unique_together': {('ride_offer', 'passenger')},
            },
        ),
    ]
