# Generated by Django 5.2.1 on 2025-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenue', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
