# Generated by Django 5.2.3 on 2025-06-13 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFRI_comotorage', '0002_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(blank=True, max_length=255, null=True)),
                ('horaire_debut', models.TimeField(blank=True, null=True)),
                ('horaire_fin', models.TimeField(blank=True, null=True)),
                ('nombre_places', models.PositiveIntegerField(default=1)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('type_utilisateur', models.CharField(choices=[('conducteur', 'Conducteur'), ('passager', 'Passager')], default='conducteur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
