# Generated by Django 5.2.1 on 2025-06-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFRI_comotorage', '0002_alter_articles_options_articles_actif_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
